### ISSUE TITLE
Are the builds/releases available?

### ISSUE THREAD

**Issue by benpillet** [thycotic/terraform-provider-tss#1]
It looks like this link is bogus: https://github.com/thycotic/terraform-provider-tss/blame/master/README.md#L10
And, I don't see anything here: https://github.com/thycotic/terraform-provider-tss/packages
or here: https://github.com/thycotic/terraform-provider-tss/releases

I'm excited to set this up in my organization.  I'll probably try building it myself in the meantime, but I'd love to see official releases.

**Comment by ericnelson** [comment]
Please publish this into the Terraform registry, even as a community plugin so we can leverage it as an automatically installed provider. 

I'd love to use this but since its not in the registry we cant use with with Terraform Cloud

**Comment by benpillet** [comment]
@ericnelson Yes, I got it built inside a docker image I was working on.  It looked something like this:
`FROM runatlantis/atlantis:v0.11.1
RUN apk add --no-cache --virtual .build-deps go ;

## Thycotic Secret Server Provider Installation
RUN go get github.com/thycotic/terraform-provider-tss

RUN mkdir -p ~atlantis/.terraform.d/plugins && \
    cp ~/go/bin/terraform-provider-tss ~atlantis/.terraform.d/plugins/

**Comment by ericnelson** [comment]
> @ericnelson Yes, I got it built inside a docker image I was working on. It looked something like this:
> 
> ```
> FROM runatlantis/atlantis:v0.11.1
> RUN apk add --no-cache --virtual .build-deps go ;
> 
> ## Thycotic Secret Server Provider Installation
> RUN go get github.com/thycotic/terraform-provider-tss
> 
> RUN mkdir -p ~atlantis/.terraform.d/plugins && \
>     cp ~/go/bin/terraform-provider-tss ~atlantis/.terraform.d/plugins/ 
> ```

Thanks, got it to build and function on Windows 10 - now to see if I can't get it in as a custom provider in TF cloud. seems to be doable if you precompile the binary for linux_amd64 and follow the instructions [https://www.terraform.io/docs/cloud/run/install-software.html](here).

**Comment by wsmelton** [comment]
A release is now available.

**Comment by benpillet** [comment]
Thanks much :-)
