### ISSUE TITLE
Unable to retrieve Provider using the required_providers method

### ISSUE THREAD

**Issue by DataDecay** [thycotic/terraform-provider-tss#12]
directly from the README.md:

```
terraform {
    required_providers {
        tss = {
            source = "terraform.thycotic.com/thycotic/tss"
            version = "~> 1.0"
        }
    }
}
```

When ran:

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
terraform.thycotic.com/thycotic/tss: could not connect to
terraform.thycotic.com: Failed to request discovery document: Get
"https://terraform.thycotic.com/.well-known/terraform.json": dial tcp: lookup
terraform.thycotic.com on 67.216.191.200:53: no such host
```

Double checked that this was not an issue with my DNS, and confirmed that `terraform.thycotic.com` does not resolve anywhere.

**Comment by aarkwright** [comment]
@thycotic-dev Please bring this back online or provide an alternative source URL.

**Comment by EndlessTrax** [comment]
This provider is now on the Terraform registry. So this issue should be resolved. 

If you encounter any further problems, please open a new issue. 

Link to the provider - https://registry.terraform.io/providers/thycotic/tss/latest
