### ISSUE TITLE
Secret ID Value

### ISSUE THREAD

**Issue by davewoodward** [thycotic/terraform-provider-tss#2]
What does the provider expect to be set as the ID value to retrieve a secret and where can you find this value in the Secret Server user interface?

**Comment by ericnelson** [comment]
The id is a number.  The easiest way to find the id is to navigate to the secret you want to use in the Secret Server web interface and look at the url, it will look something like this `https://secretserver.foo.com/SecretServer/app/#/secret/1234/general`

Provide 1234 as the ID.

**Comment by wsmelton** [comment]
As mentioned, the URL in Secret Server will provide the Secret ID you need to reference in the provider. The example below the SecretID is `1254` but it is located in a different format based on whether you are using the New or Classic UI.

The other area to find this will be via a report, as those can include the SecretID directly in the report content.

New UI:

```
https://<app url>/app/#/secret/1254/general
```

Classic UI

```
https://<app url>/SecretView.aspx?secretid=1254
```
