### ISSUE TITLE
Unable to retrieve Provider using terraform.thycotic.com/thycotic/tss

### ISSUE THREAD

**Issue by javiermarasco** [thycotic/terraform-provider-tss#21]
I am using the configuration as described in the documentation:

```
terraform {
    required_providers {
        tss = {
            source = "terraform.thycotic.com/thycotic/tss"
            version = "~> 1.0"
        }
    }
}
```

and getting the message:

```
Could not retrieve the list of available versions for provider terraform.thycotic.com/thycotic/tss: could not connect to terraform.thycotic.com: Failed to request discovery document:    
Get "https://terraform.thycotic.com/.well-known/terraform.json": dial tcp: lookup terraform.thycotic.com: no such host
```

This seems to be the same problem reported in issue [12](https://github.com/thycotic/terraform-provider-tss/issues/12)

Is this broken again? or there is a new url to use?

Thank you!

**Comment by EndlessTrax** [comment]
Where in the documentation are you seeing that? The README says the `source` should be `thycotic/tss`. Are you compiling from the source or pulling from the [Terraform registry](https://registry.terraform.io/providers/thycotic/tss/latest)?

**Comment by javiermarasco** [comment]
Thanks for the quick response, I was following [this](https://registry.terraform.io/providers/thycotic/tss/latest/docs) but with `thycotics/tss` it works, thanks for the help!

**Comment by EndlessTrax** [comment]
Glad I can help. 

I'll keep this issue open until the documentation is amended.
