### ISSUE TITLE
terraform.thycotic.com no public dns resolution 

### ISSUE THREAD

**Issue by mihaiturcu** [thycotic/terraform-provider-tss#27]
Hi,

Apparently the endpoint terraform.thycotic.com was taken down, effectively breaking the usage of this provider unless you manually download and set it up offline.

Can someone please review this?

Thanks

**Comment by EndlessTrax** [comment]
Thanks for the issue @mihaiturcu. 

It's recommended that you use `thycotic/tss` as your `source` instead of `terraform.thycotic.com`. You can get the latest version of the plugin from the [Terraform registry](https://registry.terraform.io/providers/thycotic/tss/latest).

**Comment by silviuebi** [comment]
Can you please update the documentation in the terraform registry as well?https://registry.terraform.io/providers/thycotic/tss/latest/docs

**Comment by EndlessTrax** [comment]
Good catch. Thank you, we'll get that updated.

**Comment by EndlessTrax** [comment]
Fixed with commit: 07e607ec5bf70c32cfd22cd7e03f4ab7a89a3b5a
