### ISSUE TITLE
Publish this provider in terraform registry

### ISSUE THREAD

**Issue by barryib** [thycotic/terraform-provider-tss#4]
Terraform registry now support community provider (https://registry.terraform.io/browse/providers). This will allow every user of terraform 0.13 to download community providers during the init phase.

More info :
- https://www.terraform.io/docs/registry/providers/index.html
- https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by barryib** [comment]
How can we help on this ?

**Comment by wsmelton** [comment]
@barryib this requires some setup on our side as an org on GitHub in order to set up publishing to the Terraform registry. We are working on this but unable to provide an ETA at this time.

**Comment by barryib** [comment]
To me you've already done the most difficult part with https://github.com/thycotic/terraform-provider-tss/pull/10 (probably the gpg key part is missing https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-). Now you have to sign in https://www.terraform.io/docs/registry/providers/publishing.html#signing-in (it's almost done).

FWIW, promoting a manual install for TF 0.13 is a big step back and making this provider harder to use in Terraform Cloud or Enterprise.

**Comment by wsmelton** [comment]
> FWIW, promoting a manual install for TF 0.13 is a big step back and making this provider harder to use in Terraform Cloud or Enterprise.

Terraform does not block our provider from being used in Terraform Cloud or Enterprise. We continue to work on getting the provider published.

**Comment by barryib** [comment]
> > FWIW, promoting a manual install for TF 0.13 is a big step back and making this provider harder to use in Terraform Cloud or Enterprise.
> 
> Terraform does not block our provider from being used in Terraform Cloud or Enterprise. We continue to work on getting the provider published.

I know It doesn't block it, it just make it harder. You've to build a custom image with the provider embedded. It's doable, right... But it'll be much more simpler if you can just download it automatically from the registry.

**Comment by wsmelton** [comment]
I've gotten a few blockers resolved today for Terraform Registry, extremely disappointed it requires so many rights for the user to our GitHub organization :( but is what it is I guess.

Right now it's just spinning its wheels trying to publish:
![image](https://user-images.githubusercontent.com/11204251/97922971-e8fe3700-1d22-11eb-9972-1df5e92f6c97.png)

The account being used has rights to this repository and can see those assets (the same account that owns that signing key as well).

**Comment by barryib** [comment]
Humm... Maybe because you have [terraform-provider-tss-1.0.0.tar.gz](https://github.com/thycotic/terraform-provider-tss/releases/download/v1.0.0/terraform-provider-tss-1.0.0.tar.gz) which doesn't follow the hashicorp release naming convention (`terraform-provider-{NAME}_{VERSION}_{OS}_{ARCH}.zip`) ? Just guessing and thinking aloud.

**Comment by barryib** [comment]
@wsmelton was you able to find a fix for this ?

**Comment by wb529kq** [comment]
Any progress on this ?

**Comment by barryib** [comment]
It sounds like it's now in the registry https://registry.terraform.io/providers/thycotic/tss/latest but we have issue with docs.

**Comment by EndlessTrax** [comment]
@barryib @wsmelton I've just resolved the docs issue and the new patch version is now live on the registry. 

Thank you all for your help to get this done.
