### ISSUE TITLE
Secret field

### ISSUE THREAD

**Issue by mpetka-ab** [thycotic/terraform-provider-tss#8]
It works fine with secrets as long as they have the fields "username" and "password". It does not accept fields such as "Secret access key" (from AWS programmatic access).
Error: the secret does not contain a 'Secret access key' field

**Comment by amigus** [comment]
The provider delegates to [Secret.Field()](https://github.com/thycotic/tss-sdk-go/blob/fb180c0fea800dc6941365fd54e0cc8b002b480b/server/secret.go#L60) in [tss-sdk-go](https://github.com/thycotic/tss-sdk-go)

As you can see, it tries to match based on the field's name or slug and it's case sensitive. Are you sure the exact name of the field is 'Secret access key'? What's the Slug? Can you try that instead?

**Comment by mpetka-ab** [comment]
The field name is in fact "Secret access key" the slug is "-secret-access-key" and that does work just fine. 
Thank you for your help
